version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the current directory on the host to /app inside the container
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
